describe('Travel all pages', () => {
  it('by URL', () => {
    cy.visit('/')
    cy.get('div[data-cy="home-main"]').should('be.visible')
    cy.visit('/n01')
    cy.get('div[data-cy="n01-main"]').should('be.visible')
    cy.visit('/eagleseye')
    cy.get('div[data-cy="eagles-eye-main"]').should('be.visible')
    cy.visit('/cricketnumbercount')
    cy.get('div[data-cy="cricket-number-count-main"]').should('be.visible')
    cy.visit('/history')
    cy.get('div[data-cy="history-main"]').should('be.visible')
    cy.visit('/ja')
    cy.get('div[data-cy="home-main"]').should('be.visible')
    cy.visit('/ja/n01')
    cy.get('div[data-cy="n01-main"]').should('be.visible')
    cy.visit('/ja/eagleseye')
    cy.get('div[data-cy="eagles-eye-main"]').should('be.visible')
    cy.visit('/ja/cricketnumbercount')
    cy.get('div[data-cy="cricket-number-count-main"]').should('be.visible')
    cy.visit('/ja/history')
    cy.get('div[data-cy="history-main"]').should('be.visible')
    cy.visit('/en')
    cy.get('div[data-cy="home-main"]').should('be.visible')
    cy.visit('/en/n01')
    cy.get('div[data-cy="n01-main"]').should('be.visible')
    cy.visit('/en/eagleseye')
    cy.get('div[data-cy="eagles-eye-main"]').should('be.visible')
    cy.visit('/en/cricketnumbercount')
    cy.get('div[data-cy="cricket-number-count-main"]').should('be.visible')
    cy.visit('/en/history')
    cy.get('div[data-cy="history-main"]').should('be.visible')
  })
})
export {}
