import Game from './TwoDartCombinationsGame';

test('create instance', () => {
  const game = new Game();
  expect(game).toBeTruthy();
});

test('in gaming', () => {
  const game = new Game();
  expect(game.getRound()).toBe(1);
  expect(game.getCurrentTarget()).toBe(41);
  game.addScore('20');
  expect(game.getCurrentTarget()).toBe(21);
  game.addScore('10');
  expect(game.getCurrentTarget()).toBe(11);
  game.addScore('20');
  expect(game.getTotalScore()).toEqual(0);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(42);
  game.addScore('20');
  expect(game.getCurrentTarget()).toBe(22);
  game.addScore('D11');
  expect(game.getCurrentTarget()).toBe(0);
  expect(game.getRoundScore()).toEqual(['20', 'D11', '0']);
  expect(game.getTotalScore()).toEqual(15);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(43);
  game.addScore('T20');
  expect(game.getCurrentTarget()).toBe(43);
  game.addScore('D20');
  expect(game.getCurrentTarget()).toBe(3);
  game.addScore('3');
  expect(game.getCurrentTarget()).toBe(3);
  expect(game.getTotalScore()).toEqual(15);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(44);
  game.addScore('T20');
  expect(game.getCurrentTarget()).toBe(44);
  game.addScore('D20');
  expect(game.getCurrentTarget()).toBe(4);
  game.addScore('D4');
  expect(game.getCurrentTarget()).toBe(4);
  expect(game.getTotalScore()).toEqual(15);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(45);
  game.addScore('5');
  expect(game.getCurrentTarget()).toBe(40);
  game.addScore('D20');
  expect(game.getCurrentTarget()).toBe(0);
  expect(game.getTotalScore()).toEqual(30);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(46);
  game.addScore('6');
  expect(game.getCurrentTarget()).toBe(40);
  game.addScore('D20');
  expect(game.getCurrentTarget()).toBe(0);
  expect(game.getTotalScore()).toEqual(45);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(47);
  game.addScore('7');
  expect(game.getCurrentTarget()).toBe(40);
  game.addScore('D20');
  expect(game.getCurrentTarget()).toBe(0);
  expect(game.getTotalScore()).toEqual(60);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(48);
  game.addScore('8');
  expect(game.getCurrentTarget()).toBe(40);
  game.addScore('D20');
  expect(game.getCurrentTarget()).toBe(0);
  expect(game.getTotalScore()).toEqual(75);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(49);
  game.addScore('9');
  expect(game.getCurrentTarget()).toBe(40);
  game.addScore('D20');
  expect(game.getCurrentTarget()).toBe(0);
  expect(game.getTotalScore()).toEqual(90);
  game.roundChange();
  expect(game.getCurrentTarget()).toBe(50);
  game.addScore('18');
  expect(game.getCurrentTarget()).toBe(32);
  game.addScore('D16');
  expect(game.getCurrentTarget()).toBe(0);
  expect(game.getTotalScore()).toEqual(105);
  game.roundChange();
});
